from typing import Protocol, Dict, Any, List, Optional

class IAuditManager(Protocol):
    def log(self, operation: str, table_name: str, record_id: str, new_value: Dict[str, Any]) -> None:
        ...
    def stop(self) -> None:
        ...

class ICipher(Protocol):
    def encrypt(self, data: Any) -> bytes:
        ...
    def decrypt(self, data: bytes) -> Any:
        ...

class IHashChain(Protocol):
    def init(self) -> None:
        ...
    def add(self, data: Dict[str, Any]) -> None:
        ...
    def verify(self) -> bool:
        ...
    def repair(self) -> Dict[str, Any]:
        ...
